version: "3"
services:
  app:
    command: sleep infinity
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "db"
    ports:
      - 3000:3000
    user: "ruby"
    volumes:
      - ./:/home/ruby/app
  db:
    image: "postgres:12-alpine"
